name: alex
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8 #=h8ffe710_4
  - ca-certificates=2023.5.7 #=h56e8100_0
  - glpk=5.0 #=h8ffe710_0
  # - intel-openmp=2023.1.0 #=h57928b3_46319
  - ipopt=3.14.12 #=ha9547d1_0
  - libblas=3.9.0 #=17_win64_mkl
  - libffi=3.4.2 #=h8ffe710_5
  # - libflang=5.0.0 #=h6538335_20180525
  - libhwloc=2.9.1 #=nocuda_h15da153_6
  - libiconv=1.17 #=h8ffe710_0
  - liblapack=3.9.0 #=17_win64_mkl
  - libsqlite=3.42.0 #=hcfcfb64_0
  - libxml2=2.11.4 #=hc3477c8_0
  - libzlib=1.2.13 #=hcfcfb64_5
  - llvm-meta=5.0.0=0
  - metis=5.1.0 #=h0e60522_1006
  # - mkl=2022.1.0 #=h6a75c08_874
  - mumps-seq=5.2.1 #=hb3f9cae_11
  # - openmp=5.0.0 #=vc14_1
  - openssl=3.1.1 #=hcfcfb64_1
  - pip=23.1.2=pyhd8ed1ab_0
  - ply=3.11=py_1
  # - pthreads-win32=2.9.1 #=hfa6e2cd_3
  - pyomo=6.6.1 #=py38hd3f51b4_0
  - python=3.8.17 #=h4de0772_0_cpython
  - python_abi=3.8=3_cp38
  - setuptools=68.0.0=pyhd8ed1ab_0
  - tbb=2021.9.0 #=h91493d7_0
  - tk=8.6.12 #=h8ffe710_0
  # - ucrt=10.0.22621.0 #=h57928b3_0
  # - vc=14.3 #=h64f974e_17
  # - vc14_runtime=14.36.32532 #=hfdfe4a8_17
  # - vs2015_runtime=14.36.32532 #=h05e6639_17
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6 #=h8d14728_0
  - pip:
      - antiorm==1.2.1
      - arrow==1.2.3
      - cachetools==5.3.1
      - chardet==5.1.0
      - colorama==0.4.6
      - contourpy==1.1.0
      - coolprop==6.4.3.post1
      - cvxpy==1.3.2
      - cycler==0.11.0
      - db==0.1.1
      - db-sqlite3==0.0.1
      - deepdiff==6.6.0
      - distlib==0.3.7
      - docopt==0.6.2
      - ecos==2.0.12
      - et-xmlfile==1.1.0
      - exceptiongroup==1.1.2
      - filelock==3.12.2
      - fonttools==4.40.0
      - gurobipy #==10.0.3
      - hplib==1.9
      - httplib2==0.22.0
      - importlib-resources==6.0.0
      - iniconfig==2.0.0
      - jsonpickle==3.0.1
      - kiwisolver==1.4.4
      - loguru==0.7.0
      - lxml==4.9.3
      - matplotlib==3.7.2
      - mosaik==3.1.1
      - mosaik-api==3.0.3
      - mosaik-csv==1.2.0
      - mosaik-simpy-io==0.2.4
      - networkx==3.1
      - numpy==1.24.4
      - openpyxl==3.1.2
      - ordered-set==4.1.0
      - osqp==0.6.3
      - packaging==23.1
      - paho-mqtt==1.6.1
      - pandapower==2.13.1
      - pandas==1.5.3
      - patsy==0.5.3
      - pillow==10.0.0
      - platformdirs==3.9.1
      - pluggy==1.2.0
      - pyparsing==3.0.9
      - pyproject-api==1.5.3
      - pytest==7.4.0
      - python-dateutil==2.8.2
      - pytz==2023.3
      - qdldl==0.1.7.post0
      - scipy==1.10.1
      - scs==3.2.3
      - seaborn==0.12.2
      - simpy==3.0.13
      - six==1.16.0
      - statsmodels==0.14.0
      - tabulate==0.8.10
      - tespy==0.6.3
      - tomli==2.0.1
      - tox==4.6.4
      - tqdm==4.65.0
      - tzdata==2023.3
      - virtualenv==20.24.0
      - win32-setctime==1.1.0
      - zipp==3.16.0
