name: Check Compatibility with Examples in educational_material Repository

# Workflow triggers tell GitHub when to run the workflow:
# a) when there is a new commit on the main or develop branch
# b) when a new pull request is opened to merge a branch into main or develop
on:
  push:
    branches: [ "main", "dev", "211-example-compatibility-workflow"]
  pull_request:
    branches: [ "main", "dev"]

# This workflow defines one job: check-example-compatibility
jobs:
  check-example-compatibility:
    
    # Use ubuntu-latest runner.
    # See https://github.com/actions/runner-images for a list of available runners.
    runs-on: ubuntu-latest
    
    steps:

      # Checkout a copy of this repository on the runner
      # Automatically checks out the commit that trigger the workflow
      # We use the "checkout" GitHub Action
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # Checkout a copy of the educational_material repository
      - uses: actions/checkout@v4
        with:
          repository: illuminator-team/educational_material
          path: educational_material

      # Create conda environment called illuminator
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: illuminator
          auto-activate-base: false

      # Install the dependencies for the educational_material tests
      # These are listed in educational_material/environment.yml
      - name: Install educational_material dependencies
        run: conda env update -n illuminator -f educational_material/environment.yml

      # Uninstall the Illuminator from conda environment (we want to build from source)
      - name: Uninstall Illuminator from conda environment
        shell: bash -l {0}
        run: |
          pip uninstall -y illuminator

      # Install the Illuminator dependencies listed in illuminator/environment.yml
      - name: Install illuminator dependencies
        run: conda env update -n illuminator -f environment.yml

      # Uninstall the Illuminator from conda environment (we want to build from source)
      - name: Uninstall Illuminator from conda environment
        shell: bash -l {0}
        run: |
          pip uninstall -y illuminator

      # Install the Illuminator using the current commit (build it from source)
      - name: Install the Illuminator from the current commit
        shell: bash -l {0}
        run: |
          pip install .

      # Run the educational_material tests
      - name: Run the tests
        shell: bash -l {0}
        run: |
          cd educational_material
          pytest -v
